FROM rockylinux:9

# Install required packages
RUN yum install -y firewalld python3 python3-pip

# Set up the working directory
WORKDIR /app

# Copy your Python project files into the Docker image
COPY . /app

# Install your Python project
RUN pip3 install .

# Copy the test script into the Docker image
COPY firewalld-tests.sh /firewalld-tests.sh
RUN chmod +x /firewalld-tests.sh

CMD ["/sbin/init"]
