name: Test Firewalld

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-firewalld:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t my-firewalld-image -f Dockerfile.firewalld .

    - name: Run tests
      run: |
        docker run --privileged --rm -v /sys/fs/cgroup:/sys/fs/cgroup:ro -d my-firewalld-image bash -c "./firewalld-tests.sh"
